#!/usr/bin/env bash

#: exec_target = cli

## Refresh database, files, and import configuration
##
## Usage: fin refresh

# Abort if anything fails
set -e

SITE_DIRECTORY=${SITE_DIRECTORY:-default}

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

cd ${DOCROOT_PATH}